# Generated by Django 5.1.2 on 2024-11-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_factura_cliente_accion_factura_proveedor_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFactura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=255, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('accion', models.BooleanField(default=False)),
                ('timestamp_accion', models.DateTimeField(auto_now=True)),
                ('motivo_accion', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
