# Generated by Django 5.1.2 on 2024-11-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_message_room_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='SimpleMessage',
        ),
    ]
