# Generated by Django 5.1.2 on 2024-11-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_message_simplemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplemessage',
            name='timestamp',
        ),
    ]
